# Generated by Django 3.2.13 on 2023-03-17 13:11

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('org', models.CharField(blank=True, max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_info', models.TextField(blank=True, max_length=45)),
                ('org', models.TextField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='username2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.TextField(blank=True, max_length=10)),
                ('org_token', models.TextField(blank=True, max_length=300)),
                ('org_sid', models.TextField(blank=True, max_length=300)),
                ('org_gui_name', models.URLField(blank=True, max_length=300, null=True)),
                ('org_youtube_link', models.URLField(blank=True, max_length=300, null=True)),
                ('org_facebook_link', models.URLField(blank=True, max_length=300, null=True)),
                ('org_instagram_link', models.URLField(blank=True, max_length=300, null=True)),
                ('org_tiktk_link', models.URLField(blank=True, max_length=300, null=True)),
                ('org_website_link', models.URLField(blank=True, max_length=300, null=True)),
                ('org_phone', models.CharField(blank=True, max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='OutreachRegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outreach_first_name', models.TextField(max_length=20)),
                ('outreach_last_name', models.TextField(max_length=20)),
                ('outreach_phone_number', models.TextField(max_length=10, validators=[django.core.validators.RegexValidator(message="PHONE MUST BE 10 DIGITS: '4731234567'.", regex='^\\d{10}$')])),
                ('outreach_spot', models.TextField(max_length=30)),
                ('outreach_category', models.TextField(max_length=45)),
                ('minister_category', models.TextField(max_length=45)),
                ('outreach_time', models.TextField(blank=True, max_length=300)),
                ('outreach_date', models.TextField(blank=True, max_length=300)),
                ('contact_notes', models.TextField(blank=True, max_length=300)),
                ('outreach_latitude', models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True)),
                ('outreach_longitude', models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_id', models.TextField(blank=True, max_length=20)),
                ('org_name', models.TextField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_info', models.TextField(max_length=20)),
                ('last_name_info', models.TextField(max_length=20)),
                ('phone_number_info', models.TextField(max_length=10, validators=[django.core.validators.RegexValidator(message="PHONE MUST BE 10 DIGITS: '4731234567'.", regex='^\\d{10}$')])),
                ('contact_notes_info', models.TextField(blank=True, max_length=300)),
                ('org', models.TextField(max_length=10)),
                ('contact_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='app_backend_api.categorygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usernames', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
